---

- name: Provision an OS X system
  hosts: localhost
  become: no
  become_method: sudo
#  become_user: "{{ user }}"
  connection: local
  vars:
    - connection: local
  vars_files:
    - env_vars/main.yml

  roles:
    - system
    - packages
#    - dns
    - applications
    - settings
    - dotfiles
