---
# tasks file for applications
  - name: Update Homebrew
    homebrew:
      update_homebrew=yes
    become: false

  - name: Install Brew Caskroom
    homebrew:
      name=cask
      state=present

  - name: Add the Casks
    homebrew_cask:
      name={{ item }}
      state={{ item.state|default('present') }}
    with_items: homebrew_cask_packages
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications

  - include: seil.yml tags=keyboard
  - include: karabiner.yml tags=keyboard
  - include: vagrant.yml tags=vagrant
